default: &default
  encoding: utf8
  url: <%= ENV.fetch('DATABASE_URL') { 'postgres://myuser:mypass@localhost/somedatabase' } %>

development:
  <<: *default

test:
  <<: *default
  database: app_test

production:
  <<: *default
